#!/bin/bash

SRV_MNT="$1"
if [ -z "$SRV_MNT" ]; then
    SRV_MNT="/media/servidor"
fi
./compilar_tudo
mount "$SRV_MNT"
mkdir -p "$SRV_MNT"/pole
cp -av modulos/* "$SRV_MNT"/pole/
for mo in po/locale/*/LC_MESSAGES/*.mo; do
    mkdir -p "$SRV_MNT"/pole/`dirname "$mo"`
    cp -av "$mo" "$SRV_MNT"/pole/`dirname "$mo"`
done
umount "$SRV_MNT"
